import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#131016",
    padding: 24,
    // alignItems: "center",
    // justifyContent: "center",
  },
  title: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  txtType: {
    color: "#D6E4E5",
    fontWeight: "bold",
    fontSize: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  txtUmadeb: {
    color: "#D6E4E5",
    fontWeight: "bold",
    fontSize: 15,
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: "red",
  },
  txtEventos: {
    margin: 0,
    color: "#D6E4E5",
    fontWeight: "bold",
  },
  select: {
    borderRadius: 5,
    backgroundColor: "red",
  },
  txtSelect: {
    color: "#fff",
    backgroundColor: "#131016",
    // height: 70,
  },
  viewNumber: {
    backgroundColor: "#202024",
    borderRadius: 5,
    height: 100,
    // padding: 2,
    marginTop: 10,
    flexDirection: "row",
    alignContent: "center",
    justifyContent: "center",
  },
  number: {
    width: 300,
    // padding: 10,
    fontSize: 80,
    // fontFamily: theme.FONT_FAMILY.REGULAR,
    color: "#fff",
    alignContent: "stretch",
    justifyContent: "center",
  },
  time: {
    width: "100%",
    marginTop: 5,
    paddingLeft: 15,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  txtTimeCheckin: {
    color: "#D6E4E5",
    paddingRight: 5,
    alignItems: "flex-start",
    justifyContent: "flex-start",
  },
  timeCheckin: {
    color: "yellow",
  },
  areaButto: {
    // flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonCount: {
    width: 100,
    height: 100,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 20,
    borderRadius: 100,
    backgroundColor: "#00337C",
  },
  buttonTxt: {
    color: "#FFF",
    // fontWeight: 'bold',
    fontSize: 80,
  },
});
